### ISSUE TITLE
What pairs are causing the error? Please write down the pairs that are in error.

### ISSUE THREAD

**Issue by Shin-JaeHeon** [Shin-JaeHeon/yahoo-exchange#2]
What pairs are causing the error?
 Please write down the pairs that are in error.

**Comment by Shin-JaeHeon** [comment]
What version are you using?

**Comment by pu3antasyah** [comment]
yahoo-exchange 5.7.1

Nodejs v9.4.0

**Comment by Shin-JaeHeon** [comment]
Please upgrade yahoo-exchange to the latest version.(^1.6.2)

**Comment by pu3antasyah** [comment]
After update to yahoo-exchange@1.6.2 I still facing this issue. Below is messages on fire.

`TypeError: Cannot read property 'split' of undefined
0|app      |     at number (/var/www/nodejs-project/node_modules/yahoo-exchange/index.js:10:79)
0|app      |     at parseHTML2 (/var/www/nodejs-project/node_modules/yahoo-exchange/index.js:12:34)
0|app      |     at Request.request [as _callback] (/var/www/nodejs-project/node_modules/yahoo-exchange/index.js:31:18)
0|app      |     at Request.self.callback (/var/www/nodejs-project/node_modules/request/request.js:186:22)
0|app      |     at Request.emit (events.js:160:13)
0|app      |     at Request.<anonymous> (/var/www/nodejs-project/node_modules/request/request.js:1163:10)
0|app      |     at Request.emit (events.js:160:13)
0|app      |     at IncomingMessage.<anonymous> (/var/www/nodejs-project/node_modules/request/request.js:1085:12)
0|app      |     at Object.onceWrapper (events.js:255:19)
0|app      |     at IncomingMessage.emit (events.js:165:20)

/root/.pm2/logs/app-out-0.log last 15 lines:
0|app      |     at IncomingMessage.emit (events.js:165:20)
0|app      |     at endReadableNT (_stream_readable.js:1101:12)
0|app      | 2018 05 19 23 02 14
0|app      | 2018 05 19 23 40 24
0|app      | TypeError: Cannot read property '1' of null
0|app      |     at parseHTML2 (/var/www/nodejs-project/node_modules/yahoo-exchange/index.js:14:82)
0|app      |     at Request.request [as _callback] (/var/www/nodejs-project/node_modules/yahoo-exchange/index.js:39:22)
0|app      |     at Request.self.callback (/var/www/nodejs-project/node_modules/request/request.js:186:22)
0|app      |     at Request.emit (events.js:160:13)
0|app      |     at Request.<anonymous> (/var/www/nodejs-project/node_modules/request/request.js:1163:10)
0|app      |     at Request.emit (events.js:160:13)
0|app      |     at IncomingMessage.<anonymous> (/var/www/nodejs-project/node_modules/request/request.js:1085:12)
0|app      |     at Object.onceWrapper (events.js:255:19)
0|app      |     at IncomingMessage.emit (events.js:165:20)
0|app      |     at endReadableNT (_stream_readable.js:1101:12)
`

**Comment by Shin-JaeHeon** [comment]
**I'm sorry. you should always check and maintain the latest version.**
The latest version is now 1.7.2. 

**Be careful before updating :** APIs work in a different way than before. This is because the existing method is very unstable. However, traffic usage has decreased. 
More detailed changes are in the first warning statement from Readme.md

If the same error occurs after the update, please raise the issue.

**Comment by pu3antasyah** [comment]
This issue is fixed by update to version 1.7.2, thanks a lot @Shin-JaeHeon
