### ISSUE TITLE
Error Request.emit (events.js:xxx:xxx)

### ISSUE THREAD

**Issue by pu3antasyah** [Shin-JaeHeon/yahoo-exchange#4]
pm2 show error logs like this.

`0|app      |     at Request.emit (events.js:160:13)
0|app      |     at IncomingMessage.<anonymous> (/var/www/mynode/node_modules/request/request.js:1085:12)
0|app      |     at Object.onceWrapper (events.js:255:19)
0|app      |     at IncomingMessage.emit (events.js:165:20)
0|app      | TypeError: Cannot read property 'split' of undefined
0|app      |     at number (/var/www/mynode/node_modules/yahoo-exchange/index.js:10:79)
0|app      |     at parseHTML2 (/var/www/mynode/node_modules/yahoo-exchange/index.js:12:34)
0|app      |     at Request.request [as _callback] (/var/www/mynode/node_modules/yahoo-exchange/index.js:31:18)
0|app      |     at Request.self.callback (/var/www/mynode/node_modules/request/request.js:186:22)
0|app      |     at Request.emit (events.js:160:13)
0|app      |     at Request.<anonymous> (/var/www/mynode/node_modules/request/request.js:1163:10)
0|app      |     at Request.emit (events.js:160:13)
0|app      |     at IncomingMessage.<anonymous> (/var/www/mynode/node_modules/request/request.js:1085:12)
0|app      |     at Object.onceWrapper (events.js:255:19)
0|app      |     at IncomingMessage.emit (events.js:165:20)
`

**Comment by Shin-JaeHeon** [comment]
Thank you for raising the issue.
I've identified a problem with the code.
Fortunately, I found a solution. This will apply before version 1.6.
I'll alert you again when the version that solved the error is uploaded.

**Comment by Shin-JaeHeon** [comment]
The version 1.5.6 was released when the error was resolved. 
The internal test did not produce any errors. If there is any error in using it, I would appreciate it if you could write the issue again.
